
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ship_management?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root  # ??????????
    password: 123456 # ??????????

mybatis:
  configuration:
    map-underscore-to-camel-case: true # ????????(user_pic -> userPic)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????SQL

# ???JWT??
jwt:
  secret: ship_secret_key_2025 # ???????????